#ifndef MINI_KVM_ERRORS_H
#define MINI_KVM_ERRORS_H

typedef enum MiniKVMError {
    MINI_KVM_SUCCESS = 0,
    MINI_KVM_INTERNAL_ERROR,
    MINI_KVM_UNRECOGNIZED_COMMAND,
    MINI_KVM_ARGS_FAILED,
    MINI_KVM_FAILED_FS_SETUP,
    MINI_KVM_FAILED_ALLOCATION,
    MINI_KVM_WRONG_VERSION,
    MINI_KVM_NO_DEVICE,
    MINI_KVM_FAILED_VM_CREATION,
    MINI_KVM_FAILED_IOCTL,
    MINI_KVM_UNSUPPORTED_CAPS,
    MINI_KVM_FAILED_MEMORY_REGION_CREATION,
    MINI_KVM_FAILED_VCPU_CREATION,
    MINI_KVM_FAILED_RUN,
    MINI_KVM_STATUS_COMMAND_FAILED
} MiniKVMError;

#endif /* MINI_KVM_ERRORS_H */
